security:
    providers:
        app_user_provider:
            entity:
                class: 'App\Entity\User'
                property: 'email'

    firewalls:
        main:
            # Indique le nom de la route pour le formulaire de login
            form_login:
                login_path: lego_store_login
                check_path: lego_store_login

            logout:
                path: /logout  # Cette route est celle qui déconnecte l'utilisateur
                target: /       # Après la déconnexion, l'utilisateur est redirigé vers la page d'accueil

    # Contrôle d'accès aux différentes routes
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/premium, roles: ROLE_USER }

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

# Si vous avez des configurations spécifiques pour les tests, cela devrait être dans une section dédiée
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur la plus basse pour bcrypt
                time_cost: 3 # Valeur la plus basse pour argon
                memory_cost: 10 # Valeur la plus basse pour argon
